config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :links
  resources :clicks, only: %i[index]

  namespace :api do
    resources :links, only: %i[create]
  end

  get 'sign_out', to: 'sessions#destroy'
  get 'auth/failure', to: redirect('/')
  match 'auth/:provider/callback', to: 'sessions#create', via: %i[get post]
  match '/:slug', to: 'home#url', via: %i[get post], as: 'short'
  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/click.rb
# frozen_string_literal: true

class Click < ApplicationRecord
  belongs_to :link, counter_cache: true
end

app/models/link.rb
# frozen_string_literal: true

class Link < ApplicationRecord
  belongs_to :user
  has_many :clicks, dependent: :destroy

  validates :label, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :url, presence: true

  before_validation :set_unique_slug

  def self.generate_unique_slug
    loop do
      slug = SecureRandom.base58(3)
      break slug unless Link.exists?(slug:)
    end
  end

  private

  def set_unique_slug
    self.slug = Link.generate_unique_slug if slug.blank?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :links, dependent: :destroy

  def self.from_auth_hash(auth)
    return unless /@suncoast.io$/.match?(auth.info.email)

    where(uid: auth.uid).first_or_initialize.tap do |user|
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.save!
    end
  end

  def self.from_api_key(token)
    where(email: User.encryptor.decrypt_and_verify(token)).first
  end

  def api_key
    User.encryptor.encrypt_and_sign(email)
  end

  def self.encryptor
    @encryptor ||= ActiveSupport::MessageEncryptor.new(
      Rails.application.credentials.api_token_key
    )
  end
end

app/controllers/api/links_controller.rb
# frozen_string_literal: true

module API
  class LinksController < ActionController::API
    before_action :authenticate!

    def create
      @link = authenticated_user.links.new(link_params)

      if @link.save
        render json: {
          url: short_url(@link.slug)
        }
      else
        render json: {
          errors: @link.errors
        }
      end
    end

    private

    def link_params
      params.permit(:url, :slug, :label)
    end

    def authenticate!
      head :unauthorized unless authenticated_user
    end

    def authenticated_user
      @authenticated_user ||= begin
        token = request.headers['Authorization']&.split(' ')&.last
        User.from_api_key(token) if token
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  def authenticate!
    redirect_to :root, notice: 'Authentication Required' unless signed_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue StandardError
    session[:user_id] = nil
  end

  helper_method :current_user

  def signed_in?
    !current_user.nil?
  end

  helper_method :signed_in?
end

app/controllers/clicks_controller.rb
# frozen_string_literal: true

class ClicksController < ApplicationController
  before_action :authenticate!

  # GET /links
  def index
    @pagy, @clicks = pagy(Click.all.order(created_at: :desc))
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  after_action :record_click, only: :url

  def index
    redirect_to :links if signed_in?
  end

  def url
    @link = Link.where(slug: params[:slug]).first

    if @link
      redirect_to merge_params(@link.url)
    else
      redirect_to 'https://suncoast.io'
    end
  end

  private

  def merge_params(url)
    if request.query_parameters.empty?
      url
    else
      uri = URI.parse(url)
      link_params = Rack::Utils.parse_query(uri.query)
      merged_params = request.query_parameters.merge(link_params)
      uri.query = Rack::Utils.build_query(merged_params)
      uri.to_s
    end
  end

  def record_click
    return unless @link

    @link.clicks.create({ ip_address: request.remote_ip, referrer: request.referer, user_agent: request.user_agent,
                          session: session.id })
  end
end

app/controllers/links_controller.rb
# frozen_string_literal: true

class LinksController < ApplicationController
  before_action :authenticate!
  before_action :set_link, only: %i[show edit update destroy]

  # GET /links
  def index
    scope = case params[:f]
            when 'all' then Link.all
            when 'system' then Link.joins(:user).where(users: { email: 'hello@suncoast.io' })
            else Link.where(user: current_user)
            end

    @pagy, @links = pagy(scope.order(created_at: :desc))
  end

  # GET /links/1
  def show; end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit; end

  # POST /links
  def create
    @link = current_user.links.new(link_params)

    if @link.save
      redirect_to @link, notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /links/1
  def update
    if @link.update(link_params)
      redirect_to @link, notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /links/1
  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  private

  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:url, :slug, :label)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Provides User session management
class SessionsController < ApplicationController
  protect_from_forgery except: 'create'

  def create
    @user = User.from_auth_hash(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to :links
    else
      redirect_to :root
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

require 'pagy/extras/bulma'

module ApplicationHelper
  include Pagy::Frontend
  USER_AGENT_PARSER = UserAgentParser::Parser.new

  def ua(ua_string)
    USER_AGENT_PARSER.parse(ua_string)
  end

  def sign_in_path
    "/auth/#{Rails.env.production? ? :google_oauth2 : :developer}"
  end
end

app/views/clicks/index.slim
section.section
  .container

    nav.level
      .level-left
        nav.breadcrumb aria-label="breadcrumbs"
          ul
            li
              = link_to :links do
                span.icon.is-small
                  i.fas.fa-home aria-hidden="true"
                span Links

            li.is-active
              a href="#"
                span All Clicks

    table.table.is-bordered.is-striped.is-fullwidth
      thead
        tr
          th Link
          th Time
          th IP
          th Referrer
          th UA
      tbody
        - @clicks.each do |click|
          tr
            td = link_to click.link.label, click.link
            td = time_tag click.created_at, time_ago_in_words(click.created_at)
            td = click.ip_address
            td = click.referrer
            td = ua(click.user_agent)

    == pagy_bulma_nav(@pagy)

app/views/layouts/application.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title SDG Codes
    link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"
    script defer=true src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"

  body
    nav.navbar.is-light aria-label="main navigation" role="navigation"
      .container
        .navbar-brand
          a.navbar-item href="/"
            = image_tag "icon.svg", size: '32x32'
          a.navbar-burger aria-expanded="false" aria-label="menu" data-target="navMenu" role="button"
            span aria-hidden="true"
            span aria-hidden="true"
            span aria-hidden="true"
        .navbar-menu
          .navbar-start
            - if signed_in?
              = link_to "Links", links_path, class: "navbar-item #{controller.controller_name == 'links' ? 'is-active' : ''}"
              = link_to "Clicks", clicks_path, class: "navbar-item #{controller.controller_name == 'clicks' ? 'is-active' : ''}"
          .navbar-end
            .navbar-item
              .field.is-grouped
                - if signed_in?
                  p.control
                    - current_user.name
                  p.control
                    = link_to "Sign Out", sign_out_path, class: "button is-primary"
                - else
                  p.control
                    = form_tag(sign_in_path, method: 'post') do
                      button.button.is-primary type='submit' Sign In

    section.section
      .container
        - if notice.present?
          article.message.is-success
            .message-body= notice
        = yield

    footer.footer
      .content.has-text-centered
        p
          a.has-text-grey-dark href="https://github.io/suncoast-devs/sdg-codes"
            span.icon.is-large
              i.fab.fa-github.fa-lg
        p
          a href="https://suncoast.io"
            = image_tag "banner.svg", size: "150x60"
        p
          strong SDG Codes
          '  by
          a href="https://suncoast.io" Suncoast Developers Guild
          ' . The source code is licensed
          a href="http://opensource.org/licenses/mit-license.php" MIT
          | .
          br
          | Made with
          span.icon
            i.fas.fa-heart.has-text-danger
          | in St. Petersburg, FL.

app/views/links/_form.slim
= form_with(model: link, local: true) do |form|
  - if link.errors.any?
    .message
      .message-header
        p #{pluralize(link.errors.count, "error")} prohibited this link from being saved:
      .message-body
        ul
          - link.errors.full_messages.each do |message|
            li = message

  .field.is-horizontal
    .field-label.is-normal
      = form.label :label, class: "label"
    .field-body
      .field
        .control
          = form.text_field :label, class: "input"

  .field.is-horizontal
    .field-label.is-normal
      = form.label :url, "URL", class: "label"
    .field-body
      .field
        .control
          = form.text_field :url, class: "input"

  .field.is-horizontal
    .field-label.is-normal
      = form.label :slug, class: "label"
    .field-body
      .field
        .control
          = form.text_field :slug, class: "input is-narrow"
        p.help Leave this blank for a randomly generated slug.

  .field.is-horizontal
    .field-label
    .field-body
      .field.is-grouped
        .control
          = form.submit class: "button is-primary"
        .control
          = link_to "Cancel", @link, class: "button is-text"

app/views/links/edit.slim
section.section
  .container

    nav.level
      .level-left
        nav.breadcrumb aria-label="breadcrumbs"
          ul
            li
              = link_to :links do
                span.icon.is-small
                  i.fas.fa-home aria-hidden="true"
                span Links
            li
              = link_to @link do
                span= @link.label

            li.is-active
              a href="#"
                span Edit

      .level-right
        .level-item
          = link_to @link, class: 'button is-danger' do
            span.icon
              i.fas.fa-trash
            span Delete

    = render partial: 'form', locals: { link: @link }

app/views/links/index.slim
section.section
  .container

    nav.level
      .level-left
        nav.breadcrumb aria-label="breadcrumbs"
          ul
            li.is-active
              = link_to :links do
                span.icon.is-small
                  i.fas.fa-home aria-hidden="true"
                span Links
      .level-right
        .level-item
          = link_to :new_link, class: 'button' do
            span.icon
              i.fas.fa-plus
            span Link

    .tabs.is-boxed
      ul
        li[class=(!params[:f] && "is-active")]
          = link_to "Mine", :links
        li[class=(params[:f] == 'all' && "is-active")]
          = link_to "All", links_path(f: :all)
        li[class=(params[:f] == 'system' && "is-active")]
          = link_to "System", links_path(f: :system)

    table.table.is-bordered.is-striped.is-fullwidth
      thead
        tr
          th Label
          th Short URL
          th Clicks
          th Creator
      tbody
        - @links.each do |link|
          tr
            td = link_to link.label, link
            td = short_url(link.slug)
            td = link.clicks_count
            td 
              - if link.user
                = link.user.name
              - else
                em System

    == pagy_bulma_nav(@pagy)

app/views/links/new.slim
section.section
  .container

    nav.level
      .level-left
        nav.breadcrumb aria-label="breadcrumbs"
          ul
            li
              = link_to :links do
                span.icon.is-small
                  i.fas.fa-home aria-hidden="true"
                span Links

            li.is-active
              a href="#"
                span New

    = render partial: 'form', locals: { link: @link }

app/views/links/show.slim
section.section
  .container

    nav.level
      .level-left
        nav.breadcrumb aria-label="breadcrumbs"
          ul
            li
              = link_to :links do
                span.icon.is-small
                  i.fas.fa-home aria-hidden="true"
                span Links
            li.is-active
              a href="#"
                span= @link.label

      .level-right
        .level-item
          = link_to [:edit, @link], class: 'button' do
            span.icon
              i.fas.fa-edit
            span Edit

    table.table.is-striped.is-fullwidth
      tr
        th Created By
        td = @link.user.name

      tr
        th Short URL
        td = short_url @link.slug

      tr
        th URL
        td = @link.url

      tr
        th Click Count
        td = @link.clicks_count

    h4.title.is-4 Clicks

    table.table.is-bordered.is-striped.is-fullwidth
      thead
        tr
          th Time
          th IP
          th Referrer
          th UA
      tbody
        - @link.clicks.order(created_at: :desc).each do |click|
          tr
            td = time_tag click.created_at, time_ago_in_words(click.created_at)
            td = click.ip_address
            td = click.referrer
            td
              .tags
                span.tag[title=ua(click.user_agent)]
                  = ua(click.user_agent).family
                span.tag
                  = ua(click.user_agent).os.family